version: "3"
services:
  db-service:
    build: ./db-service/
    ports:
      - "8083:8082"
    volumes:
      - ./mount-point:/mnt/mount-point

  cab-service:
    build: ./cab-service/
    ports:
      - "8080:8080"
    volumes:
      - ./mount-point/:/mnt/mount-point:ro

  wallet-service:
    build: ./wallet-service/
    ports:
      - "8082:8080"
    volumes:
      - ./mount-point:/mnt/mount-point:ro

  ride-service:
    build: ./ride-service/
    ports:
      - "8081:8080"
    volumes:
      - ./mount-point:/mnt/mount-point:ro
