apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service-deployment
  labels:
    app: db-deployment
spec:
  selector:
    matchLabels:
      app: db-deployment
  template:
    metadata:
      labels:
        app: db-deployment
    spec:
      containers:
      - name: db-service-container
        image: project-1_db-service
        imagePullPolicy: Never
        ports:
        - containerPort: 9092
        volumeMounts:
        - mountPath: /mnt/mount-point
          name: mount-point
      volumes:
      - name: mount-point
        hostPath:
          path: /home/project/mount-point-db
          type: Directory

